config/routes.rb
Rails.application.routes.draw do
  root to: "posts#index"
  get 'access/menu'
  get 'access/login'
  post 'access/login'
  get 'access/logout'
  get "access/admin_login"
  post "access/admin_login"
  get "access/admin_logout"
  get 'admin', to: 'access#menu'
  get "/dank", to: "posts#dank"
  get "/fresh", to: "posts#fresh"
  get '/top', to: "posts#top"
  resources :posts do
    resources :reports
    resources :likes
    resources :comments do
      resources :likes
    end
  end
  resources :comments do
    resources :reports
    resources :comments
  end
  resources :users do
    resources :reports
  end
  post 'posts/:id', to: "posts#destroy"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :commentable, polymorphic: true
  has_many :comments, as: :commentable
  has_many :likes, as: :likeable
  has_many :reports, as: :reportable
  belongs_to :user
  validates :content, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :find_commentable
  before_action :find_comment, only: [:show, :update, :destroy, :edit]

  def new
    @comment = Comment.new
  end

  def show
    if !session[:admin_id]
      redirect_to dank_path
    end
  end

  def create
    @comment = @commentable.comments.new comment_params
    @comment.save
    redirect_to request.referrer
  end

  def edit
  end

  def update
    @comment.update(comment_params)
    redirect_to post_path(@comment.commentable_id)
  end

  def destroy

    @comment.destroy
    redirect_to request.referrer
  end

  private

  def comment_params
    params.require(:comment).permit(:content, :commentable_id, :commentable_type, :user_id)
  end

  def find_commentable
    @commentable = Comment.find_by_id(params[:comment_id]) if params[:comment_id]
    @commentable = Post.find_by_id(params[:post_id]) if params[:post_id]
  end

  def find_comment
    @comment = Comment.find(params[:id])
  end
end

app/views/comments/_comment.html.erb
<li>
  <div class="container-fluid shadow-lg p-4 mb-4 bg-white">

  <% if comment.user %>
  <%= link_to image_tag(comment.user.avatar_url, class: "shadow mb-1 rounded-lg", style: "max-height:150px; max-width:150px"), user_path(comment.user) %> <%=link_to comment.user.display_name, user_path(comment.user)%><br>
  <% else %>
  (Deleted User)
  <% end %>
  <small>Replied: <%= time_ago_in_words(comment.created_at) %> ago</small>

  <% if comment.updated_at != comment.created_at %>
    <small><%= "(edited " + time_ago_in_words(comment.updated_at) + " ago)" %></small>
  <% end %>
  <h3><%= comment.content %></h3>

  <h6>Likes: <%= comment.likes.count %></h6>
  <ul class="nav">
    <% if @current_user %>
    <li class="nav-item">
      <%= button_to "Like", post_comment_likes_path(comment_id: comment.id, post_id: @post), method: "POST", params: {like: {user_id: @current_user, likeable_id: comment.id, likeable_type: "Comment"}}, class: "nav-link" %>
    </li>
    <li class="nav-item">
      <%= link_to "Report", new_comment_report_path(comment), class: "nav-link" %>
    </li>
    <% end %>
    <% if comment.user %>
    <% if @current_user == comment.user.id %>
    <li class="nav-item">
      <%= link_to "Edit Comment", edit_comment_path(comment), method: :get, class: "nav-link" %>
    </li>
    <li class="nav-item">
      <%= link_to "Delete Comment", comment_path(comment), method: :delete, data: {confirm: "Are you sure?"}, class: "nav-link" %>
    </li>
    <% end %>
    <% end %>

  </ul>

  <% if @current_user %>
    <%= form_tag [comment, Comment.new] do %>
      <%= text_area_tag "comment[content]" %><br/>
      <%= button_to "Reply", comment_comments_path(comment_id: comment.id), params: {comment: {user_id: @current_user, commentable_id: comment.id, commentable_type: "Comment"}} %>
    <% end %><br>
  <% end %>
</div>
  <ul style="list-style:none;">
      <%= render partial: 'comments/comment', collection: comment.comments %>
  </ul>

</li>

app/views/comments/edit.html.erb
<div class="container">
 <%= form_for @comment do |c| %>
 <%= c.label "Edit Comment:" %><br>
 <%= c.text_area :content %><br>
 <%= c.submit %>
 <% end %>
</div>

app/views/comments/show.html.erb
<% if @comment.user %>
<%= link_to image_tag(@comment.user.avatar_url, class: "shadow mb-1 rounded-lg", style: "max-height:150px; max-width:150px"), user_path(@comment.user) %> <%=link_to @comment.user.display_name, user_path(@comment.user)%><br>
<% else %>
(Deleted User)
<% end %>
<small>Replied: <%= time_ago_in_words(@comment.created_at) %> ago</small>

<% if @comment.updated_at != @comment.created_at %>
  <small><%= "(edited " + time_ago_in_words(@comment.updated_at) + " ago)" %></small>
<% end %>
<h3><%= @comment.content %></h3>
<%= link_to "Delete Comment", comment_path(@comment), method: :delete, data: {confirm: "Are you sure?"}, class: "nav-link" %>