config/routes.rb
Rails.application.routes.draw do
  root to: "posts#index"
  get 'access/menu'
  get 'access/login'
  post 'access/login'
  get 'access/logout'
  get "access/admin_login"
  post "access/admin_login"
  get "access/admin_logout"
  get 'admin', to: 'access#menu'
  get "/dank", to: "posts#dank"
  get "/fresh", to: "posts#fresh"
  get '/top', to: "posts#top"
  resources :posts do
    resources :reports
    resources :likes
    resources :comments do
      resources :likes
    end
  end
  resources :comments do
    resources :reports
    resources :comments
  end
  resources :users do
    resources :reports
  end
  post 'posts/:id', to: "posts#destroy"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/access_controller.rb
class AccessController < ApplicationController
  def menu
    if @admin
      @reports = Report.all
    else
      redirect_to dank_path
    end
  end

  def login
    if @current_user
      redirect_to dank_path
    end
    if params[:username].present? && params[:password].present?
      found_user = User.where(username: params[:username]).first
      if found_user
        authorized_user = found_user.authenticate(params[:password])
      end
    end
    if authorized_user
      session[:user_id] = authorized_user.id
      flash[:notice] = "You successfully logged in."
      redirect_to user_path(authorized_user)
    else
      flash.now[:notice] = "Invalid username/password combination."
    end
  end

  def logout
    session[:user_id] = nil
    flash[:notice] = "Successfully Logged Out."
    redirect_to '/'
  end

  def admin_login
    if @admin
      redirect_to access_menu_path
    end
    if params[:username].present? && params[:password].present?
      found_admin = Admin.where(username: params[:username]).first
      if found_admin
        authorized_admin = found_admin.authenticate(params[:password])
      end
    end
    if authorized_admin
      session[:admin_id] = authorized_admin.id
      flash[:notice] = "You successfully logged in."
      redirect_to access_menu_path
    else
      flash.now[:notice] = "Invalid username/password combination."
    end
  end

  def admin_logout
    session[:admin_id] = nil
    flash[:notice] = "Successfully Logged Out."
    redirect_to '/'
  end

end

app/views/access/admin_login.html.erb
<div class="login">
  <%= form_tag access_admin_login_path, :method => :post do %>
  <%= label_tag(:username) %>
        <%= text_field_tag(:username, params[:username]) %>
      <%= label_tag(:password) %>
      <%= password_field_tag(:password) %>
        <%= submit_tag("Log In") %>

  <% end %>
</div>

app/views/access/login.html.erb
<div class="container shadow-lg p-4 mb-4 bg-white">
  <div class="login container">
    <%= form_tag access_login_path, :method => :post do %>
    <%= label_tag(:username) %>
          <%= text_field_tag(:username, params[:username]) %>
        <%= label_tag(:password) %>
        <%= password_field_tag(:password) %>
          <%= submit_tag("Log In") %>

    <% end %>
    <h2><%= link_to "Or sign up", new_user_path %></h2>
  </div>

app/views/access/menu.html.erb
<h1>Reports</h1>
<ul>
<% @reports.each do |report| %>
<li><%= report.content %>
<%= link_to report.reportable_type, report.reportable %>
<%= button_to "Delete Report", [report.reportable, report], method: :delete %>
</li>
<% end %>
</ul>