config/routes.rb
Rails.application.routes.draw do
  root to: "posts#index"
  get 'access/menu'
  get 'access/login'
  post 'access/login'
  get 'access/logout'
  get "access/admin_login"
  post "access/admin_login"
  get "access/admin_logout"
  get 'admin', to: 'access#menu'
  get "/dank", to: "posts#dank"
  get "/fresh", to: "posts#fresh"
  get '/top', to: "posts#top"
  resources :posts do
    resources :reports
    resources :likes
    resources :comments do
      resources :likes
    end
  end
  resources :comments do
    resources :reports
    resources :comments
  end
  resources :users do
    resources :reports
  end
  post 'posts/:id', to: "posts#destroy"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  # has_attached_file :image, styles: { large: "800x800>", medium: "300x300>", thumb: "100x100>" }
  # validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
  belongs_to :user
  has_many :comments, as: :commentable
  has_many :likes, as: :likeable
  has_many :reports, as: :reportable
  validates :title, presence: true
  validates_format_of :image_url, :with => %r{\.(png|jpg|jpeg|gif|mp4|mpeg4|gifv)$}i, multiline: true
  validates :image_url, presence: true

  def self.sort_by_new
    Post.all.sort_by do |item|
      item.created_at
    end.reverse
  end

  def self.sort_by_top
     Post.all.sort_by do |item|
       item.likes.count
     end.reverse
  end

  def self.sort_by_dank
    Post.all.sort_by do |item|
     ((Time.now.to_i - item.updated_at.to_i) / 60 / 60).to_f - item.likes.count.to_f 
    end
  end


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    redirect_to dank_path
  end

  def dank
    @posts = Post.sort_by_dank
  end

  def top
    @posts = Post.sort_by_top
  end

  def fresh
    @posts = Post.sort_by_new
  end

  def new
    set_current_user
    @post = Post.new
    session[:user_id] = @current_user
  end

  def create
    post = Post.new(post_params)
    if post.valid?
      post.save
      redirect_to post
    else
      flash[:notice] = "You must attach an image."
      redirect_to new_post_path
    end
  end

  def destroy
    @post = Post.find(params[:id])
    begin
    @post.destroy
    rescue
    end
    redirect_to '/'
  end

  def show
    @post = Post.find(params[:id])
    @comments = @post.comments.sort_by {|comment| comment.likes.count}
    @comments = @comments.reverse
    set_current_user
  end

  private

  def post_params
    params.require(:post).permit(:title, :image_url, :user_id)
  end
end

app/views/posts/_post_list.html.erb
<div class="container-fluid">

<% @posts.each do |p| %>
  <div class="container shadow-lg p-4 mb-4 bg-white rounded">
  <h1><%= p.title %></h1><br>
  <% if p.user %>
  Uploaded by: <br><%= link_to image_tag(p.user.avatar_url, class: "shadow mb-1 rounded-lg", style: "max-height:150px; max-width:150px"), user_path(p.user) %>
  <strong><%= link_to p.user.display_name, user_path(p.user)  %></strong>
  <% else %>
  Uploaded by: (Deleted User)
  <% end %>
  <br><small>Uploaded: <%= time_ago_in_words(p.created_at) %> ago</small><br>
  <%= link_to image_tag(p.image_url, class: "img-responsive"), post_path(p) %>
  <% if @current_user %><br>
  <%= button_to "Like", post_likes_path(p), method: "POST", params: {like: {user_id: @current_user, likeable_id: p.id, likeable_type: "Post"}} %><br>
  <% end %>
  Likes: <%= p.likes.count %>
  </div><br>
<% end %>
</div>

app/views/posts/dank.html.erb
  <div class="container text-light">
    <h4>Sorted by Dank</h4>
  </div>

<%= render "posts/post_list" %>

app/views/posts/fresh.html.erb
<div class="container text-light">
<h4>Sorted by Fresh</h4>
</div>

<%= render "posts/post_list" %>

app/views/posts/index.html.erb
<% if flash[:notice] %>
<%= flash[:notice] %>
<% end %>

<ul>
<% @posts.each do |p| %>
  <li><div class="post">
  <h2><%= p.title %></h2><br>
  Uploaded by: <%= link_to image_tag(p.user.avatar.url(:thumb)), user_path(p.user) %>
  <%= link_to p.user.display_name, user_path(p.user)  %>
  Uploaded on: <%= p.created_at.strftime("%b, %d, %Y") %> at <%= p.created_at.strftime("%I:%M %p %Z") %><br>
  <%= link_to image_tag(p.image.url), post_path(p) %></div></li><br>
<% end %>
</ul>

app/views/posts/new.html.erb
<div class="container shadow-lg p-4 mb-4 bg-white">
  <br>
    <h1>Submit New Post:</h1>
  <br>
    <%= form_for @post do |f| %>
  <div class="field container-fluid">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <br>
  <div class="field">
    <%= f.label "Paste image URL here" %>
    <%= f.text_field :image_url %>
    (We recommend Imgur.com, must end in .gif, .jpg, .jpeg, or .png)
    <%= f.hidden_field :user_id, value: session[:user_id] %>
   </div>
    <%= f.submit %>
    <% end %>
  </div>

app/views/posts/show.html.erb
<div class="container shadow-lg p-4 mb-4 bg-white rounded-lg">
  <h1><%= @post.title %><br></h1>
<% if @post.user %>
Uploaded by: <br> <%= link_to image_tag(@post.user.avatar_url, style: "max-height:150px; max-width:150px", class: "shadow mb-1 rounded-lg"), user_path(@post.user) %> <%= link_to @post.user.display_name, user_path(@post.user)%> <br>
<% else %>
Uploaded by: (Deleted User)
<% end %>
<small>Uploaded: <%= time_ago_in_words(@post.created_at) %> ago</small><br>
<%= image_tag @post.image_url, class: "img-responsive " %><br>

Likes: <%= @post.likes.count %><br><br>
<ul class="nav">
  <li class="nav-item">

    <% if @current_user %>
    <%= button_to "Like", post_likes_path(@post), method: "POST", params: {like: {user_id: @current_user, likeable_id: @post.id, likeable_type: "Post"}}, class: "nav-link" %><br>
    <% end %>
  </li>
  <li class="nav-item">
    <% if @post.user || @admin %>
    <% if @current_user == @post.user.id || @admin %>
    <%= link_to "Delete Post", post_path(@post), method: :delete, data: {confirm: "Are you sure?"}, class: "nav-link" %>
    <% end %>
    <% end %>
  </li>
  <li class="nav-item">
    <% if @current_user %>
    <%= link_to "Report", [:new, @reportable, :report], method: :get, class: "nav-link"  %>
    <% end %>
  </li>
</ul>



<% if @current_user %>
<%= form_tag post_comments_path(@post) do  %>
  <%= text_area_tag "comment[content]" %><br>
  <%= button_to "Submit Comment", post_comments_path(@post), method: "POST", params: {comment: {user_id: @current_user, commentable_id: @post.id, commentable_type: "Post"}} %>
<% end %>
<% end %>

</div>


<div class="container">

<h2>Comments:</h2>

<% if !@current_user %>
  <h4>Please <%= link_to "sign in", access_login_path %> to comment or like</h4>
  <% end %>
<ul class="list-unstyled">
  <%= render(partial: 'comments/comment', collection: @comments) %>
</ul>
</div>

app/views/posts/top.html.erb
<div class="container text-light">
<h4>Sorted by Top</h4>
</div>

<%= render "posts/post_list" %>